### ISSUE TITLE
own packages are not visible from ansiblite command line 

### ISSUE THREAD

**Issue by ownport** [ownport/ansiblite#2]
```sh
$ ./bin/ansiblite -h
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./bin/ansiblite/__main__.py", line 2, in <module>
  File "./bin/ansiblite/main.py", line 7, in <module>
ImportError: No module named ansiblite.utils.pyenv
```

**Comment by ownport** [comment]
The attempt to run ansiblite as module is successful
```sh
$ python -m ansiblite -h
Usage: __main__.py -[options] (-h for help)

Options:
  -h, --help            show this help message and exit
  -m MODULE_PATH, --module-path=MODULE_PATH
                        REQUIRED: full path of module source to execute
  -a MODULE_ARGS, --args=MODULE_ARGS
                        module argument string
$
```
